### ISSUE TITLE
doesn't seem to build on Racket 6.2.1

### ISSUE THREAD

**Issue by dented42** [jeapostrophe/lux#1]
in the dependencies list the info.rkt file lists that gui-lib 1.13 is required, but Racket 6.2.1 seems to come with gui-lib 1.9. The package manager tells me I can't install 1.13 as it's in the installation wide scope, and I'm a little nervous about upgrading it in case the rest of the system depends on 1.9.

Can lux be modified to work with the older version, or will we just have to wait for a new release of Racket to ship with the updated libraries?

**Comment by jeapostrophe** [comment]
If you force the install, it will work. The new version of the gum-lib is
just needed to get access to the real pixels on OS X rather than scaled
points. Everything will behave properly, provided you don't try to use that
feature.

Jay

On Tue, Sep 1, 2015 at 2:03 PM, dented42 notifications@github.com wrote:

> in the dependencies list the info.rkt file lists that gui-lib 1.13 is
> required, but Racket 6.2.1 seems to come with gui-lib 1.9. The package
> manager tells me I can't install 1.13 as it's in the installation wide
> scope, and I'm a little nervous about upgrading it in case the rest of the
> system depends on 1.9.
> 
> Can lux be modified to work with the older version, or will we just have
> to wait for a new release of Racket to ship with the updated libraries?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeapostrophe/lux/issues/1.

## 

Jay McCarthy
http://jeapostrophe.github.io

```
       "Wherefore, be not weary in well-doing,
  for ye are laying the foundation of a great work.
```

And out of small things proceedeth that which is great."
                          - D&C 64:33
