### ISSUE TITLE
What's with the names?

### ISSUE THREAD

**Issue by cwebber** [jeapostrophe/lux#6]
Hi!  So I've started using Lux for some small demo projects and I *really* like it.  Great job all around!

Though one thing does confuse me.... I can't figure out where these names came from, and how to map them in my head to anything I know.  What's the history behind the name choices for "chaos", "word", and even "fiat"?  My guess is that "word" is jokingly similar to "world".  I'm not sure about the others.

I guess feel free to just close this bug with the reasoning, but maybe putting something in the documentation, or maybe even changing the words to more familiar ones, may help (maybe even borrowing from big-bang?).  I know that for me the strangeness of the names made me unsure that I could grok what did what when initially reading the documentation (I will say that working on an example does help clear it up.)

**Comment by jeapostrophe** [comment]
Hi Christopher, The names are based on the names in HtDP/2e, but with a biblical, rather than scientific tone.

In 2htdp/universe, you use "big-bang" to create a "world" or "universe", but "lux" is playfully based on Biblical names. So, the library is called "lux" (light) and you use turn the "chaos" into "light" with a "word" and you get the thing start by calling "fiat-lux" (let there be light) rather than "big-bang".

https://en.wikipedia.org/wiki/Let_there_be_light

**Comment by cwebber** [comment]
Aha!  Thanks for that explaination :)
